name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate Docker with GCP
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app
        gcloud run deploy node-app \
          --image $IMAGE_NAME \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
